#include $(srctree)/drivers/misc/mediatek/Makefile.custom

imgsensor_isp6s-objs += \
	$(subdrv-rpath)/gc02m1bpd2278mipimono_Sensor.o
imgsensor_isp6s-objs += \
	$(subdrv-rpath)/gc02m1bpd2278mipimono_otp.o
