name: build
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      device:
        type: choice
        description: '請選擇裝置名稱'        
        required: true
        options:
        - 'Y77'
      target:
        type: choice
        description: '請選擇裝置內核CONFIG'
        required: true
        options:
        - 'mgk_64_k510_defconfig_PD2219'

jobs:
  build:
    name: ${{ github.actor }}編譯嘅${{ github.event.inputs.device }}核心
    runs-on: ubuntu-22.04
    steps:

      - name: 設定5GIB嘅SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: 安裝所需嘅環境
        run: |
          sudo apt-get update
          sudo apt-get install git automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3
          sudo apt install -yqq bison build-essential device-tree-compiler flex gcc-aarch64-linux-gnu python3 python3-dev python3-venv swig
          mkdir -p $GITHUB_WORKSPACE/workdir
          cd $GITHUB_WORKSPACE/workdir
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: 獲取 ZyCromerZ-Clang20 工具鏈
        run: |
          wget https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20241109-release/Clang-20.0.0git-20241109.tar.gz -O $GITHUB_WORKSPACE/workdir/zyc_clang20.tar.gz
          mkdir $GITHUB_WORKSPACE/workdir/clang
          tar zxvf $GITHUB_WORKSPACE/workdir/zyc_clang20.tar.gz -C $GITHUB_WORKSPACE/workdir/clang
  
      - name: 獲取 ${{ github.event.inputs.device }} 嘅核心源碼
        run: |
          git clone --recursive https://github.com/$GITHUB_REPOSITORY/ --depth 1 $GITHUB_WORKSPACE/workdir/source

      - name: 設定 Ccache 嘅容量
        uses: hendrikmuhs/ccache-action@v1.2
        with:
         key: build-kernel-mido-kernel
         max-size: 2G

      - name: 編譯 ${{ github.event.inputs.device }} 核心
        run: |
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }})
          export ARCH="arm64"
          export SUBARCH="arm64"
          export PATH="$GITHUB_WORKSPACE/workdir/clang/bin/:$PATH"
          export CROSS_COMPILE="aarch64-linux-gnu-"
          cd $GITHUB_WORKSPACE/workdir/source
          make O=out mgk_64_k510_defconfig CC="ccache clang"
          cat arch/arm64/configs/${{ github.event.inputs.target }} >> out/.config
          make O=out ${{ github.event.inputs.target }} CC="ccache clang"
          make -j$(nproc --all) O=out CC="ccache clang" 2>&1 | tee kernel.log

      - name: 上傳編譯日志
        uses: actions/upload-artifact@v4
        with:
          name: android_kernel_mt6855_${{ github.event.inputs.target }}_${{ env.BUILD_TIME }}_kernel.log
          path: workdir/source/kernel.log

      - name: 上傳 ${{ github.event.inputs.device }} 嘅 AnyKernel3 文檔
        if: env.CHECK_FILE_IS_OK == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: mt6855_${{ github.event.inputs.target }}_${{ env.BUILD_TIME }}
          path: out/arch/arm64/boot/*
          
      - name: 上傳 DTB 備份
        if: env.CHECK_FILE_IS_OK == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: DTB
          path: out/arch/arm64/boot/dts/mediatek/*
